version: '1'

zookeeper:
  image: wurstmeister/zookeeper:3.4.6
  expose:
  - "2181"

kafka:
  image: wurstmeister/kafka:2.11-2.0.0
  depends_on:
  - zookeeper
  ports:
  - "9092:9092"
  environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1  #insert here your IP address
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

services:
  cassandra:
    image: bitnami/cassandra:latest
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    restart: unless-stopped

  cassandra2:
    image: bitnami/cassandra:3
    ports:
      - 7001:7000
      - 9043:9042
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    restart: unless-stopped

  cassandra3:
    image: bitnami/cassandra:3
    ports:
      - 7002:7000
      - 9044:9042
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    restart: unless-stopped


